[tool.poetry]
name = "discinstock_api"
version = "1.0.0"
description = "API for discinstock.no. Currently serving discs endpoint with search functionality"
authors = ["Sondre William Kaldhussæter-Knutsen <knutsensondre@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.63.0"
uvicorn = {extras = ["standard"], version = "^0.13.4"}
pymongo = "^3.11.3"
motor = "^2.4.0"
gunicorn = "^20.1.0"
python-dotenv = "^0.17.1"

[tool.poetry.dev-dependencies]
pytest = "5.3.5"
coverage = { version = "5.0.3", extras = ["toml"]}
black = "^19.10b0"
isort = { version = "^4.3.21", extras = ["pyproject"]}
requests = "^2.23.0"

[tool.poetry.scripts]
start = "app.app:main"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"